[package]
name = "tutorial13_Modules"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ADDED DEPENDENCIES
rand = "0.8.5"
