[package]
name = "tutorial14_vector_string_hashmap"
version = "0.1.0"
edition = "2021"

# [http]
# check-revoke = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# unicode-segmentation = "1.10.1"
